### Tests for Applying Gains Matrix

In [2]:
import cupy as cp
import numpy as np
from utils import *
from zp_puregpu_funcs_py import *
from invcov import *

hera_cal is not installed. Some gridding features unavailable.
pyfof is not installed. Some gridding features unavailable.


In [3]:
apply_gains_to_mat?
# undo_zeropad?

Signature:
apply_gains_to_mat(
    gains: cupy.ndarray,
    mat: cupy.ndarray,
    edges: cupy.ndarray,
    ant_1_array: cupy.ndarray,
    ant_2_array: cupy.ndarray,
    xp: Any,
    is_zeropadded: bool = True,
)
Docstring:
Apply a pair of complex gains to a matrix. Utilizes the Re/Im split.
Only accounts for "one half" of the gain application, meaning the 
function is really performing eg. (g_1g_2*\Delta_{1,2}), where it is 
understood that antenna's 1 and 2 belong to the baseline sitting at
the same row as that baseline row in the \Delta (\Sigma) matrix. Note that 
although the matrix provided may be zeropadded, the gain matrix is zeropadded 
here and as such, should always be provided in an un-zeropadded (original) format.

NOTE: Could be smart in the future to wrap the zeropadding of the gain 
    matrix in a separate function.

Params
------
gains
    1D array of Re/Im alternating gains to be applied to the source or
    diffuse matrices. Contains one set of Re/Im gains for all an

In [4]:
summarize_benchmark_results?

Signature: summarize_benchmark_results(function, *args)
Docstring:
Use the CuPy benchmark function and nicely print out just the
total time spent on both the gpu and the cpu.
File:      ~/corrcal_gpu_pipeline/pipeline/utils.py
Type:      function

In [46]:
#simulation params relevant for testing application of gains to a matrix
n_ant = 4
n_bl = 30
n_gains = 2*n_bl
n_eig = 3
xp = cp  #run things on the gpu using cupy

#this might be the easiest (and most general) way to devise an edges
# array, though we hard code an ex. edges array to be sure it fits
# the desired format of having no odd entries.
edges = (xp.unique(xp.random.randint(1, n_bl/2-1, size = n_ant)*2))
edges = xp.concatenate((xp.array([0]), edges, xp.array([n_bl])))
print(f"The edges of the redundant blocks have indices{edges}")

#some random noise, diffuse, and source covariance matrices
xp = cp
sim_diff_mat = xp.random.rand(n_bl, n_eig, dtype = 'float64')
sim_gains = cp.random.rand(n_gains, dtype = 'float64') #Re/Im split + ant1 & ant 2 = 4*n_ant
ant_1_array = cp.arange(n_bl//2)
ant_2_array = cp.arange(n_bl//2)

#zeropad the noise, diff, source mats
zp_sim_diff_mat, largest_block, n_blocks = zeroPad(sim_diff_mat, edges, return_inv=False)

#Need to reshape to give an extra dimension of n_blocks to be compatible with inv cov routine
sim_diff_mat_3d = zp_sim_diff_mat.reshape(n_blocks, largest_block, n_eig)

The edges of the redundant blocks have indices[ 0  2  6 12 30]


In [47]:
applied_gains = apply_gains_to_mat(sim_gains, sim_diff_mat_3d, edges, ant_1_array, ant_1_array, cp, True)

In [48]:
print(f"Input mat has shape {sim_diff_mat_3d.shape}")
print()
print(f"Gains applied mat has shape {applied_gains.shape}")
print()
print(f"The mat with gains applied looks like:\n\n{applied_gains}")

Input mat has shape (4, 18, 3)

Gains applied mat has shape (4, 18, 3)

The mat with gains applied looks like:

[[[0.17559102 0.0913616  0.00364314]
  [0.12997649 0.1974795  0.13590692]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.53270293 0.47820383 0.19558848]
  [0.41928636 0.4148223  0.50739083]
  [0.71030479 0.58174487 1.04845778]
  [1.01862861 1.10776441 0.46124678]
  [0.         0.         0.        ]
  [0.         0.         0.        

#### Random Debugging tests

In [49]:
m = np.random.rand(2, 5, 3)
g = np.random.rand(10)

gs = g[:, None] * g[:, None]
gs = gs.reshape(m.shape[0], m.shape[1], 1)

print(gs.shape)
print(m.shape)
print(g.shape)
print(m)
print(m[:, ::2])
out = gs[:, ::2] * m[:, ::2]

(2, 5, 1)
(2, 5, 3)
(10,)
[[[0.16167031 0.34526009 0.69396311]
  [0.57070825 0.88329105 0.69632166]
  [0.88639889 0.80214    0.35460003]
  [0.72238019 0.93171779 0.32625203]
  [0.02055513 0.4832205  0.42432656]]

 [[0.66092006 0.6281286  0.34457089]
  [0.09029565 0.25141056 0.35615979]
  [0.18335952 0.55637183 0.68558055]
  [0.73721374 0.53216768 0.50785471]
  [0.84552749 0.06368828 0.76446976]]]
[[[0.16167031 0.34526009 0.69396311]
  [0.88639889 0.80214    0.35460003]
  [0.02055513 0.4832205  0.42432656]]

 [[0.66092006 0.6281286  0.34457089]
  [0.18335952 0.55637183 0.68558055]
  [0.84552749 0.06368828 0.76446976]]]


In [50]:
a = np.arange(5)
b = np.arange(5,10)
c = np.random.rand((a.shape[0] + b.shape[0]))
print(c)
d = c[a]
e = c[b]

print(d)
print()
print(e)
print()
print(np.concatenate((d, e)))
print()
aa = np.concatenate((d, e))

print(aa[:int(len(aa)/2)])

print(aa[int(len(aa)/2):])

[0.45303294 0.61432632 0.95228438 0.67605443 0.86879742 0.1074288
 0.43278445 0.71144623 0.02337054 0.22414874]
[0.45303294 0.61432632 0.95228438 0.67605443 0.86879742]

[0.1074288  0.43278445 0.71144623 0.02337054 0.22414874]

[0.45303294 0.61432632 0.95228438 0.67605443 0.86879742 0.1074288
 0.43278445 0.71144623 0.02337054 0.22414874]

[0.45303294 0.61432632 0.95228438 0.67605443 0.86879742]
[0.1074288  0.43278445 0.71144623 0.02337054 0.22414874]


#### Check ZP computes the same thing as corrcal

In [51]:
#Current corrcal gain application function
def apply_gains_to_mat_corrcal(gains, mat, ant_1_array, ant_2_array):
    """Apply a gain-like matrix to a provided matrix."""
    complex_gains = gains[::2] + 1j*gains[1::2]
    gain_mat = (
        complex_gains[ant_1_array,None] * complex_gains[ant_2_array,None].conj()
    )
    out = np.zeros_like(mat)
    out[::2] = gain_mat.real * mat[::2] - gain_mat.imag * mat[1::2]
    out[1::2] = gain_mat.imag * mat[::2] + gain_mat.real * mat[1::2]
    return out

In [52]:
#simulation params relevant for testing application of gains to a matrix
n_ant = 15
n_bl = 2*n_ant
n_gains = 4*n_ant
n_eig = 3
xp = cp  #run things on the gpu using cupy

#this might be the easiest (and most general) way to devise an edges
# array, though we hard code an ex. edges array to be sure it fits
# the desired format of having no odd entries.
edges = (xp.unique(xp.random.randint(1, n_bl/2-1, size = 3)*2))
edges = xp.concatenate((xp.array([0]), edges, xp.array([n_bl])))
print(f"The edges of the redundant blocks have indices{edges}")

#some random noise, diffuse, and source covariance matrices
xp = cp
sim_diff_mat = xp.random.rand(n_bl, n_eig, dtype = 'float64')
sim_gains = cp.random.rand(n_gains, dtype = 'float64') #Re/Im split + ant1 & ant 2 = 4*n_ant
ant_1_array = cp.arange(n_ant)
ant_2_array = cp.arange(n_ant, 2*n_ant)

#zeropad the noise, diff, source mats
zp_sim_diff_mat, largest_block, n_blocks = zeroPad(sim_diff_mat, edges, return_inv=False)

#Need to reshape to give an extra dimension of n_blocks to be compatible with inv cov routine
sim_diff_mat_3d = zp_sim_diff_mat.reshape(n_blocks, largest_block, n_eig)


The edges of the redundant blocks have indices[ 0  2  8 18 30]


In [53]:
# out_corrcal = apply_gains_to_mat_corrcal(sim_gains, sim_diff_mat, ant_1_array, ant_2_array)
out_gpu = apply_gains_to_mat(sim_gains, sim_diff_mat_3d, edges, ant_1_array, ant_2_array, cp)
out_gpu_corrcal = apply_gains_to_mat(sim_gains, sim_diff_mat, edges, ant_1_array, ant_2_array, cp, False)
out_gpu_resh = undo_zeropad(out_gpu, edges, cp)

In [54]:
#should return True if my routine computes the same thing as the current corrcal routine
print(cp.allclose(out_gpu_resh, out_gpu_corrcal))

True


#### Timing test for np vs cp versions

In [43]:
#simulation params relevant for testing application of gains to a matrix
n_bl = 240000  # something like 2*N_ant^2 for Re/Im split
n_ant = 512
n_gains = 2*n_bl  #one for each antenna and one for each Re and Im part
n_eig = 3
xp = cp  #run things on the gpu using cupy

#this might be the easiest (and most general) way to devise an edges
# array, though we hard code an ex. edges array to be sure it fits
# the desired format of having no odd entries.
if xp == cp:

    edges = (xp.unique(xp.random.randint(1, n_bl/2-1, size = n_ant)*2))
    edges = xp.concatenate((xp.array([0]), edges, xp.array([n_bl])))
    print(f"The edges of the redundant blocks have indices{edges}")

    #some random noise, diffuse, and source covariance matrices
    sim_diff_mat = xp.random.rand(n_bl, n_eig, dtype = 'float64')
    sim_gains = cp.random.rand(n_gains, dtype = 'float64') #Re/Im split + ant1 & ant 2 = 4*n_ant
    
    #leave as n_bl/2 since indexex into cplex gains which are not Re/Im split
    ant_1_array = cp.arange(n_bl//2) 
    ant_2_array = cp.arange(n_bl//2)

    #zeropad the noise, diff, source mats
    zp_sim_diff_mat, largest_block, n_blocks = zeroPad(sim_diff_mat, edges, return_inv=False)

    #Need to reshape to give an extra dimension of n_blocks to be compatible with inv cov routine
    sim_diff_mat_3d = zp_sim_diff_mat.reshape(n_blocks, largest_block, n_eig)

elif xp == np:
    edges = (xp.unique(xp.random.randint(1, n_bl/2-1, size = n_ant)*2))
    edges = xp.concatenate((xp.array([0]), edges, xp.array([n_bl])))
    print(f"The edges of the redundant blocks have indices{edges}")

    #some random noise, diffuse, and source covariance matrices
    sim_diff_mat = xp.random.rand(n_bl, n_eig).astype('float64')
    sim_gains = xp.random.rand(n_gains).astype('float64') #Re/Im split + ant1 & ant 2 = 4*n_ant
    ant_1_array = xp.arange(n_bl//2)
    ant_2_array = xp.arange(n_bl//2)

    #zeropad the noise, diff, source mats
    # zp_sim_diff_mat, largest_block, n_blocks = zeroPad(sim_diff_mat, edges, return_inv=False)

    #Need to reshape to give an extra dimension of n_blocks to be compatible with inv cov routine
    # sim_diff_mat_3d = zp_sim_diff_mat.reshape(n_blocks, largest_block, n_eig)

print(len(edges))

The edges of the redundant blocks have indices[     0    450    582    840   1894   2002   2378   2414   2992   5950
   6110   6524   7130   7172   7564   7956   8364   9218  10098  10322
  10746  10788  10864  11148  11538  12016  12066  12562  12930  14366
  14976  15266  15440  15868  17198  18384  18606  18962  19182  20220
  20422  20484  20568  20970  21710  22080  22152  22806  22998  24198
  24748  25418  25642  27326  27514  27612  28662  28688  28836  28930
  28992  29304  29446  29536  29698  30366  30586  30624  31568  32222
  32284  32496  33708  33980  34880  35488  35502  35796  36916  37332
  37662  37814  38192  38694  39190  39684  39690  40364  41266  41456
  42080  42552  44400  44518  45404  46074  46088  46390  46824  48336
  48904  50238  50552  50920  51522  52146  53342  53394  53566  53988
  54504  55294  55690  55974  56744  56798  57696  58672  58742  59156
  59424  59554  59882  60070  60260  61202  61286  63004  64116  64264
  64626  65050  65674  66336  6

In [42]:
print(type(sim_diff_mat))
print(type(sim_gains))
summarize_benchmark_results(apply_gains_to_mat, sim_gains, sim_diff_mat, edges, ant_1_array, ant_2_array, xp, False)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Time on cpu: 0.014120s
Time on gpu: 0.014666s


In [45]:
print(type(sim_diff_mat))
print(type(sim_gains))
summarize_benchmark_results(apply_gains_to_mat, sim_gains, sim_diff_mat_3d, edges, ant_1_array, ant_2_array, xp, True)

<class 'cupy.ndarray'>
<class 'cupy.ndarray'>
Time on cpu: 0.002538s
Time on gpu: 0.004685s
