In [4]:
def fun(x,y):
    z = x*y
    # return z
    w = x/y
    return w

In [5]:
fun(3,3)

1.0

In [7]:
import numpy as np
a1 = np.arange(1_000_000, dtype=np.float128)
a2 = np.arange(1_000_000, dtype=np.float128)
print(a1.dtype)


print(np.allclose(a1, a2))

float128
True


In [47]:
seed = 24
n = 20
m = 10

In [48]:
np.random.seed(seed)
a = np.random.normal(size=n)
np.random.seed(seed)
b = np.random.normal(size=m)
np.all(a[:m] == b)

np.True_

In [ ]:
np.random.seed(seed)
a1 = np.random.normal(size=n)
a2 = np.random.normal(size=n)

np.random.seed(seed)
b1 = np.random.normal(size=m)
b2 = np.random.normal(size=m)

np.all(a2[:m] == b2[:m])

np.False_

In [50]:
print(a1[:m])
# print(a2[:m])
print(b1[:m])
# print(b2[:m])

[ 1.32921217 -0.77003345 -0.31628036 -0.99081039 -1.07081626 -1.43871328
  0.56441685  0.29572189 -1.62640423  0.2195652 ]
[ 1.26410337  0.29003478 -1.9702885   0.80390589  1.03055033  0.11809794
 -0.02185333  0.04684071 -1.62875286 -0.39236059]


In [55]:
np.random.seed(11)
a = np.random.rand(15)
b = np.random.rand(15)
print(a)
print(b)

[0.18026969 0.01947524 0.46321853 0.72493393 0.4202036  0.4854271
 0.01278081 0.48737161 0.94180665 0.85079509 0.72996447 0.10873607
 0.89390417 0.85715425 0.16508662]
[0.63233401 0.02048361 0.11673727 0.31636731 0.15791231 0.75897959
 0.81827536 0.34462449 0.3187988  0.11166123 0.08395314 0.71272594
 0.5995434  0.05567368 0.47979728]


In [56]:
np.random.seed(11)
a = np.random.rand(10)
b = np.random.rand(10)
print(a)
print(b)

[0.18026969 0.01947524 0.46321853 0.72493393 0.4202036  0.4854271
 0.01278081 0.48737161 0.94180665 0.85079509]
[0.72996447 0.10873607 0.89390417 0.85715425 0.16508662 0.63233401
 0.02048361 0.11673727 0.31636731 0.15791231]


In [ ]:
A = np.arange(10)
print(A[:5+1])

[0 1 2 3 4 5]


In [75]:
a = np.tril_indices(4, k = -1)
print(a)

g = np.random.rand(100)
print(g)

print(g[a, None]*g[a, None])
print(g[a, None])


(array([1, 2, 2, 3, 3, 3]), array([0, 0, 1, 0, 1, 2]))
[0.33868847 0.53224018 0.67834956 0.10519407 0.75528363 0.5569211
 0.5171444  0.38087046 0.31464712 0.89050462 0.99377647 0.17521486
 0.21150118 0.66703409 0.7645629  0.82296581 0.30244554 0.20910031
 0.07256924 0.37633227 0.56248474 0.87255135 0.03304442 0.08965531
 0.65314512 0.67132106 0.12413149 0.0963657  0.02797631 0.64873407
 0.27985678 0.24099295 0.66454899 0.12100047 0.53641326 0.09092484
 0.06574941 0.66853317 0.79161448 0.46242777 0.40214606 0.7015488
 0.07604138 0.27828288 0.90526741 0.94895581 0.03839609 0.00306412
 0.76788412 0.45187828 0.76243046 0.64298306 0.44796639 0.70998097
 0.60452724 0.01571606 0.46612052 0.88200465 0.78028444 0.65492812
 0.62157872 0.81661236 0.29134246 0.39410514 0.63065627 0.82095578
 0.32138868 0.16847811 0.27225628 0.43897635 0.09846298 0.62833551
 0.89648003 0.34219781 0.95637894 0.41962811 0.53574379 0.97673088
 0.71003349 0.50550928 0.75455802 0.47330733 0.72157398 0.22234908
 0.076895

In [79]:
arr = np.arange(20)
print(arr[-5:])

[15 16 17 18 19]


In [21]:
print(int(2**10.5))

1448


In [23]:
def fun(n):
    return 3*n**2 -3*n + 1

print(fun(7))

127
