In [1]:
import cupy as cp
import numpy as np
from cupyx.profiler import benchmark

In [2]:
arr = cp.arange(10)

In [2]:
arr = np.arange(10)

for (start, stop) in (zip(arr[2:], arr[1:])):
    print((start, stop))

(2, 1)
(3, 2)
(4, 3)
(5, 4)
(6, 5)
(7, 6)
(8, 7)
(9, 8)


In [7]:
import cupy as cp
print(cp.cuda.runtime.runtimeGetVersion())  # This shows the CUDA runtime version
print(cp.cuda.runtime.driverGetVersion())   # This shows the CUDA driver version


12040
0


In [8]:
arr = cp.random.rand(3, 2, 2)
print(arr.shape)

CUDARuntimeError: cudaErrorInsufficientDriver: CUDA driver version is insufficient for CUDA runtime version

In [16]:
arr2 = cp.random.rand(3, 4)
print(arr2)
print(cp.diagonal(arr2, axis1=-2))

[[0.02379579 0.15108471 0.77317719 0.68826071]
 [0.64246177 0.26207391 0.13598067 0.88615679]
 [0.21977118 0.77220318 0.72369275 0.78412778]]
[0.02379579 0.26207391 0.72369275]


In [25]:
print(arr)
diags = cp.diagonal(arr, axis1=-2, axis2=-1)
print(diags)
print(cp.sum(diags))

[[[0.6658514  0.30448025]
  [0.23440571 0.57411087]]

 [[0.01336878 0.67031363]
  [0.86601476 0.33006527]]

 [[0.55458585 0.49397364]
  [0.50090923 0.75417174]]]
[[0.6658514  0.57411087]
 [0.01336878 0.33006527]
 [0.55458585 0.75417174]]
2.8921539096151307


In [31]:
import numpy as np

tarr = np.arange(12)
tarr = tarr.reshape(3, 2, 2)
print(tarr)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [40]:
diags = np.diagonal(tarr, axis2 = 1, axis1 = 2)
print(np.sum(diags))
print(diags)

33
[[ 0  3]
 [ 4  7]
 [ 8 11]]


In [48]:
arr1 = cp.arange(1000000)
arr2 = cp.arange(10000000)

def arr_mult(a, b):
    return cp.matmul(arr1, arr2)
    cp.cuda.Stream.null.synchronize()
    # return arr1 + arr2

def arr_fft(a):
    ans = cp.fft.fft(a)
    cp.cuda.Stream.null.synchronize()
    

# result = benchmark(arr_mult, (arr1, arr2), n_repeat=1000)
# print(result)

result = benchmark(arr_fft, (arr1,), n_repeat=100)
print(result)

arr_fft             :    CPU:  1740.414 us   +/- 108.981 (min:  1528.282 / max:  2206.120) us     GPU-0:  1798.195 us   +/- 142.286 (min:  1550.336 / max:  2225.152) us


In [39]:
import cupy as cp
import time

arr1 = cp.arange(1000000)
arr2 = cp.arange(1000000)

def arr_mult(a, b):
    return cp.matmul(a, b)

def arr_fft(a):
    return cp.fft.fft(a)

# Warm-up runs
arr_mult(arr1, arr2)
arr_fft(arr1)
cp.cuda.Stream.null.synchronize()

# Benchmark arr_mult
start = time.time()
for _ in range(100):
    arr_mult(arr1, arr2)
cp.cuda.Stream.null.synchronize()
end = time.time()
print(f"Time for arr_mult: {end - start} seconds")

# Benchmark arr_fft
start = time.time()
for _ in range(100):
    arr_fft(arr1)
cp.cuda.Stream.null.synchronize()
end = time.time()
print(f"Time for arr_fft: {end - start} seconds")


Time for arr_mult: 0.033081769943237305 seconds
Time for arr_fft: 0.08926677703857422 seconds
