# Testing routines to undo zeropadding

In [1]:
import sys
from pathlib import Path
parent_dir = Path.cwd().parent
sys.path.insert(0, str(parent_dir))

In [2]:
import numpy as np
import cupy as cp
import corrcal
from zp_puregpu_funcs_py import *

hera_cal is not installed. Some gridding features unavailable.
pyfof is not installed. Some gridding features unavailable.


In [3]:
undo_zeroPad?

Signature: undo_zeroPad(array, edges)
Docstring: <no docstring>
File:      ~/corrcal_gpu_pipeline/pipeline/zp_puregpu_funcs_py.py
Type:      function

### Test undo-zeropadding in 1D (ie. the noise matrix) 

Very simple test array and edges example...

In [4]:
edges = cp.array([0, 5, 10, 13, 20])
test_arr = cp.random.rand(int(edges[-1]))
print(test_arr)

[0.45568807 0.2769425  0.54445498 0.094581   0.91127019 0.26501181
 0.41316763 0.86983604 0.77602281 0.74437176 0.48180383 0.69959689
 0.10811315 0.3628429  0.96817271 0.29996798 0.2823649  0.06114765
 0.39595157 0.73995672]


Start by zeropadding and printing out the results

In [5]:
zp_test_arr, lb, nbs = zeroPad(test_arr, edges, return_inv=False)
print(zp_test_arr)
zp_test_arr_rs = zp_test_arr.reshape(nbs, lb, 1)
print(zp_test_arr_rs)

[0.45568807 0.2769425  0.54445498 0.094581   0.91127019 0.
 0.         0.26501181 0.41316763 0.86983604 0.77602281 0.74437176
 0.         0.         0.48180383 0.69959689 0.10811315 0.
 0.         0.         0.         0.3628429  0.96817271 0.29996798
 0.2823649  0.06114765 0.39595157 0.73995672]
[[[0.45568807]
  [0.2769425 ]
  [0.54445498]
  [0.094581  ]
  [0.91127019]
  [0.        ]
  [0.        ]]

 [[0.26501181]
  [0.41316763]
  [0.86983604]
  [0.77602281]
  [0.74437176]
  [0.        ]
  [0.        ]]

 [[0.48180383]
  [0.69959689]
  [0.10811315]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.3628429 ]
  [0.96817271]
  [0.29996798]
  [0.2823649 ]
  [0.06114765]
  [0.39595157]
  [0.73995672]]]


Now let's do the same for the undo_zeropad function and see if the matrices are the same as what we started with.

In [6]:
print(zp_test_arr_rs.shape[2])
undo_zp = undo_zeroPad(zp_test_arr_rs, edges)
print(undo_zp)
print(np.allclose(test_arr, undo_zp))
# assert((np.allclose(test_arr, undo_zp)))

1
[0.45568807 0.2769425  0.54445498 0.094581   0.91127019 0.26501181
 0.41316763 0.86983604 0.77602281 0.74437176 0.48180383 0.69959689
 0.10811315 0.3628429  0.96817271 0.29996798 0.2823649  0.06114765
 0.39595157 0.73995672]
True


### Tests for undo zeropad with 2d matrices

Rinse-repeat for the 2d (ie. diffuse and source sky) case.

In [16]:
edges = cp.array([0, 5, 10, 13, 20])
test_arr = cp.random.rand(int(edges[-1]), 2)
print(test_arr)

[[0.39734525 0.92827381]
 [0.39862971 0.33229095]
 [0.02322109 0.57955064]
 [0.53173797 0.90777962]
 [0.77498156 0.04474777]
 [0.18037789 0.3577055 ]
 [0.95467493 0.0652618 ]
 [0.80297727 0.99002871]
 [0.93002892 0.14359595]
 [0.81240668 0.57511969]
 [0.97541933 0.59465268]
 [0.72618303 0.60669523]
 [0.33468049 0.15685786]
 [0.57992108 0.14179442]
 [0.57851981 0.53275192]
 [0.7940801  0.08235259]
 [0.56534169 0.57446941]
 [0.32007591 0.03185446]
 [0.94408233 0.04142484]
 [0.77478412 0.82436307]]


In [17]:
zp_test_arr, lb, nbs = zeroPad(test_arr, edges, return_inv=False)
# print(zp_test_arr)
zp_test_arr_rs = zp_test_arr.reshape(nbs, lb, 2)
print(zp_test_arr_rs)

[[[0.39734525 0.92827381]
  [0.39862971 0.33229095]
  [0.02322109 0.57955064]
  [0.53173797 0.90777962]
  [0.77498156 0.04474777]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.18037789 0.3577055 ]
  [0.95467493 0.0652618 ]
  [0.80297727 0.99002871]
  [0.93002892 0.14359595]
  [0.81240668 0.57511969]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.97541933 0.59465268]
  [0.72618303 0.60669523]
  [0.33468049 0.15685786]
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.57992108 0.14179442]
  [0.57851981 0.53275192]
  [0.7940801  0.08235259]
  [0.56534169 0.57446941]
  [0.32007591 0.03185446]
  [0.94408233 0.04142484]
  [0.77478412 0.82436307]]]


In [19]:
print(zp_test_arr_rs.shape)
undo_zp_2d = undo_zeroPad(zp_test_arr_rs, edges)
print(undo_zp_2d)
# print(test_arr)
print(np.allclose(undo_zp_2d, test_arr))

(4, 7, 2)
[[0.39734525 0.92827381]
 [0.39862971 0.33229095]
 [0.02322109 0.57955064]
 [0.53173797 0.90777962]
 [0.77498156 0.04474777]
 [0.18037789 0.3577055 ]
 [0.95467493 0.0652618 ]
 [0.80297727 0.99002871]
 [0.93002892 0.14359595]
 [0.81240668 0.57511969]
 [0.97541933 0.59465268]
 [0.72618303 0.60669523]
 [0.33468049 0.15685786]
 [0.57992108 0.14179442]
 [0.57851981 0.53275192]
 [0.7940801  0.08235259]
 [0.56534169 0.57446941]
 [0.32007591 0.03185446]
 [0.94408233 0.04142484]
 [0.77478412 0.82436307]]
True
