# Testing routines to undo zeropadding

In [1]:
import sys
from pathlib import Path
parent_dir = Path.cwd().parent
sys.path.insert(0, str(parent_dir))

In [2]:
import numpy as np
import cupy as cp
import corrcal
from zp_puregpu_funcs_py import *

hera_cal is not installed. Some gridding features unavailable.
pyfof is not installed. Some gridding features unavailable.


In [3]:
# undo_zeroPad?

### Test undo-zeropadding in 1D (ie. the noise matrix) 

Very simple test array and edges example...

In [4]:
edges = cp.array([0, 5, 10, 13, 20])
test_arr = cp.random.rand(int(edges[-1]))
print(test_arr)

[0.04411245 0.36228259 0.64924228 0.36869379 0.10237472 0.08186196
 0.50075827 0.10284657 0.99927225 0.21698521 0.78915022 0.16537118
 0.92129361 0.0297659  0.53684975 0.0235271  0.00534362 0.31980375
 0.02813703 0.41771776]


Start by zeropadding and printing out the results

In [5]:
zp_test_arr, lb, nbs = zeroPad(test_arr, edges, return_inv=False)
print(zp_test_arr)
# zp_test_arr_rs = zp_test_arr.reshape(nbs, lb, 1)
# print(zp_test_arr_rs)

[[[0.04411245]
  [0.36228259]
  [0.64924228]
  [0.36869379]
  [0.10237472]
  [0.        ]
  [0.        ]]

 [[0.08186196]
  [0.50075827]
  [0.10284657]
  [0.99927225]
  [0.21698521]
  [0.        ]
  [0.        ]]

 [[0.78915022]
  [0.16537118]
  [0.92129361]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.0297659 ]
  [0.53684975]
  [0.0235271 ]
  [0.00534362]
  [0.31980375]
  [0.02813703]
  [0.41771776]]]


Now let's do the same for the undo_zeropad function and see if the matrices are the same as what we started with.

In [7]:
print(zp_test_arr.shape[2])
undo_zp = undo_zeroPad(zp_test_arr, edges)
print(undo_zp)
print(np.allclose(test_arr, undo_zp))
# assert((np.allclose(test_arr, undo_zp)))

1
[0.04411245 0.36228259 0.64924228 0.36869379 0.10237472 0.08186196
 0.50075827 0.10284657 0.99927225 0.21698521 0.78915022 0.16537118
 0.92129361 0.0297659  0.53684975 0.0235271  0.00534362 0.31980375
 0.02813703 0.41771776]
True


### Tests for undo zeropad with 2d matrices

Rinse-repeat for the 2d (ie. diffuse and source sky) case.

In [8]:
edges = cp.array([0, 5, 10, 13, 20])
test_arr = cp.random.rand(int(edges[-1]), 2)
print(test_arr)

[[0.27587439 0.26706896]
 [0.59914895 0.61915993]
 [0.04069359 0.32184427]
 [0.15778495 0.65465593]
 [0.22977843 0.03690285]
 [0.13364811 0.22877208]
 [0.19742524 0.88320555]
 [0.16439838 0.73647889]
 [0.01346697 0.54072241]
 [0.76327465 0.67114665]
 [0.82165825 0.50432529]
 [0.83585424 0.53257927]
 [0.23188378 0.83749432]
 [0.26323447 0.02914254]
 [0.83820057 0.15533584]
 [0.16850065 0.98351476]
 [0.71932287 0.00677419]
 [0.23084008 0.96297756]
 [0.21624478 0.51037871]
 [0.47664181 0.84621973]]


In [9]:
zp_test_arr, lb, nbs = zeroPad(test_arr, edges, return_inv=False)
print(zp_test_arr)
# zp_test_arr_rs = zp_test_arr.reshape(nbs, lb, 2)
# print(zp_test_arr_rs)

[[[0.27587439 0.26706896]
  [0.59914895 0.61915993]
  [0.04069359 0.32184427]
  [0.15778495 0.65465593]
  [0.22977843 0.03690285]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.13364811 0.22877208]
  [0.19742524 0.88320555]
  [0.16439838 0.73647889]
  [0.01346697 0.54072241]
  [0.76327465 0.67114665]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.82165825 0.50432529]
  [0.83585424 0.53257927]
  [0.23188378 0.83749432]
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.26323447 0.02914254]
  [0.83820057 0.15533584]
  [0.16850065 0.98351476]
  [0.71932287 0.00677419]
  [0.23084008 0.96297756]
  [0.21624478 0.51037871]
  [0.47664181 0.84621973]]]


In [10]:
print(zp_test_arr.shape)
undo_zp_2d = undo_zeroPad(zp_test_arr, edges)
print(undo_zp_2d)
# print(test_arr)
print(np.allclose(undo_zp_2d, test_arr))

(4, 7, 2)
[[0.27587439 0.26706896]
 [0.59914895 0.61915993]
 [0.04069359 0.32184427]
 [0.15778495 0.65465593]
 [0.22977843 0.03690285]
 [0.13364811 0.22877208]
 [0.19742524 0.88320555]
 [0.16439838 0.73647889]
 [0.01346697 0.54072241]
 [0.76327465 0.67114665]
 [0.82165825 0.50432529]
 [0.83585424 0.53257927]
 [0.23188378 0.83749432]
 [0.26323447 0.02914254]
 [0.83820057 0.15533584]
 [0.16850065 0.98351476]
 [0.71932287 0.00677419]
 [0.23084008 0.96297756]
 [0.21624478 0.51037871]
 [0.47664181 0.84621973]]
True
