# Testing routines to undo zeropadding

In [1]:
import sys
from pathlib import Path
parent_dir = Path.cwd().parent
sys.path.insert(0, str(parent_dir))

In [2]:
import numpy as np
import cupy as cp
import corrcal
from zp_puregpu_funcs_py import *

hera_cal is not installed. Some gridding features unavailable.
pyfof is not installed. Some gridding features unavailable.


In [3]:
# undo_zeroPad?

### Test undo-zeropadding in 1D (ie. the noise matrix) 

Very simple test array and edges example...

In [4]:
edges = cp.array([0, 5, 10, 13, 20])
test_arr = cp.random.rand(int(edges[-1]))
print(test_arr)

[0.31216953 0.95700615 0.28591977 0.05853091 0.28177927 0.93862132
 0.1635097  0.45243419 0.49085678 0.07481701 0.73359287 0.03994731
 0.36833208 0.57626928 0.09972421 0.46749162 0.28549418 0.66608369
 0.22995831 0.88776615]


Start by zeropadding and printing out the results

In [16]:
zp_test_arr, lb, nbs = zeroPad(test_arr, edges, return_inv=False)
print(zp_test_arr)
# zp_test_arr_rs = zp_test_arr.reshape(nbs, lb, 1)
# print(zp_test_arr_rs)

[[0.31216953 0.95700615 0.28591977 0.05853091 0.28177927 0.
  0.        ]
 [0.93862132 0.1635097  0.45243419 0.49085678 0.07481701 0.
  0.        ]
 [0.73359287 0.03994731 0.36833208 0.         0.         0.
  0.        ]
 [0.57626928 0.09972421 0.46749162 0.28549418 0.66608369 0.22995831
  0.88776615]]


Now let's do the same for the undo_zeropad function and see if the matrices are the same as what we started with.

In [17]:
print(zp_test_arr.ndim)
undo_zp = undo_zeroPad(zp_test_arr, edges, ReImsplit=True)
print(undo_zp)
print(np.allclose(test_arr, undo_zp))
# assert((np.allclose(test_arr, undo_zp)))

2
[0.31216953 0.95700615 0.28591977 0.05853091 0.28177927 0.93862132
 0.1635097  0.45243419 0.49085678 0.07481701 0.73359287 0.03994731
 0.36833208 0.57626928 0.09972421 0.46749162 0.28549418 0.66608369
 0.22995831 0.88776615]
True


### Tests for undo zeropad with 2d matrices

Rinse-repeat for the 2d (ie. diffuse and source sky) case.

In [18]:
edges = cp.array([0, 5, 10, 13, 20])
test_arr = cp.random.rand(int(edges[-1]), 2)
print(test_arr)

[[0.51372689 0.98437428]
 [0.12355219 0.54773304]
 [0.26537302 0.38350291]
 [0.31746626 0.95822445]
 [0.08528488 0.43627221]
 [0.7539037  0.20894249]
 [0.72742653 0.87979218]
 [0.59376037 0.65342356]
 [0.63700411 0.39447519]
 [0.45412183 0.13905288]
 [0.22518833 0.04239845]
 [0.2922947  0.6733247 ]
 [0.02159667 0.09481259]
 [0.56348772 0.3652465 ]
 [0.58453463 0.92656202]
 [0.22541622 0.92586948]
 [0.4451919  0.1711913 ]
 [0.70837065 0.14547145]
 [0.53710524 0.29760421]
 [0.18516163 0.39602788]]


In [21]:
zp_test_arr, lb, nbs = zeroPad(test_arr, edges, return_inv=False)
print(zp_test_arr)
# zp_test_arr_rs = zp_test_arr.reshape(nbs, lb, 2)
# print(zp_test_arr_rs)

[[[0.51372689 0.98437428]
  [0.12355219 0.54773304]
  [0.26537302 0.38350291]
  [0.31746626 0.95822445]
  [0.08528488 0.43627221]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.7539037  0.20894249]
  [0.72742653 0.87979218]
  [0.59376037 0.65342356]
  [0.63700411 0.39447519]
  [0.45412183 0.13905288]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.22518833 0.04239845]
  [0.2922947  0.6733247 ]
  [0.02159667 0.09481259]
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.56348772 0.3652465 ]
  [0.58453463 0.92656202]
  [0.22541622 0.92586948]
  [0.4451919  0.1711913 ]
  [0.70837065 0.14547145]
  [0.53710524 0.29760421]
  [0.18516163 0.39602788]]]


In [23]:
print(zp_test_arr.shape)
undo_zp_2d = undo_zeroPad(zp_test_arr, edges, ReImsplit=True)
print(undo_zp_2d)
# print(test_arr)
print(np.allclose(undo_zp_2d, test_arr))

(4, 7, 2)
[[0.51372689 0.98437428]
 [0.12355219 0.54773304]
 [0.26537302 0.38350291]
 [0.31746626 0.95822445]
 [0.08528488 0.43627221]
 [0.7539037  0.20894249]
 [0.72742653 0.87979218]
 [0.59376037 0.65342356]
 [0.63700411 0.39447519]
 [0.45412183 0.13905288]
 [0.22518833 0.04239845]
 [0.2922947  0.6733247 ]
 [0.02159667 0.09481259]
 [0.56348772 0.3652465 ]
 [0.58453463 0.92656202]
 [0.22541622 0.92586948]
 [0.4451919  0.1711913 ]
 [0.70837065 0.14547145]
 [0.53710524 0.29760421]
 [0.18516163 0.39602788]]
True
