In [3]:
import numpy as np
a = np.random.rand(2,3,1)
b = np.random.rand(2,3)

In [6]:
print(a.shape)
print(b.shape)

(2, 3, 1)
(2, 3)


In [7]:
print(a@b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [12]:
ar = np.arange(10)
na = np.arange(1,6)
print(ar)
print(na)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]


In [13]:
ar = ar.reshape(na[-1],2)
print(ar)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
