In [2]:
import cupy as cp
import numpy as np

In [13]:
arr = np.arange(10)

for (start, stop) in (zip(arr[2:], arr[1:])):
    print((start, stop))

(2, 1)
(3, 2)
(4, 3)
(5, 4)
(6, 5)
(7, 6)
(8, 7)
(9, 8)


In [2]:
arr = cp.random.rand(3, 2, 2)
print(arr.shape)

(3, 2, 2)


In [16]:
arr2 = cp.random.rand(3, 4)
print(arr2)
print(cp.diagonal(arr2, axis1=-2))

[[0.02379579 0.15108471 0.77317719 0.68826071]
 [0.64246177 0.26207391 0.13598067 0.88615679]
 [0.21977118 0.77220318 0.72369275 0.78412778]]
[0.02379579 0.26207391 0.72369275]


In [25]:
print(arr)
diags = cp.diagonal(arr, axis1=-2, axis2=-1)
print(diags)
print(cp.sum(diags))

[[[0.6658514  0.30448025]
  [0.23440571 0.57411087]]

 [[0.01336878 0.67031363]
  [0.86601476 0.33006527]]

 [[0.55458585 0.49397364]
  [0.50090923 0.75417174]]]
[[0.6658514  0.57411087]
 [0.01336878 0.33006527]
 [0.55458585 0.75417174]]
2.8921539096151307


In [31]:
import numpy as np

tarr = np.arange(12)
tarr = tarr.reshape(3, 2, 2)
print(tarr)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [40]:
diags = np.diagonal(tarr, axis2 = 1, axis1 = 2)
print(np.sum(diags))
print(diags)

33
[[ 0  3]
 [ 4  7]
 [ 8 11]]
