In [1]:
import cupy as cp
import torch

# 1. Make a CuPy array on the GPU
cp_arr = cp.arange(12, dtype=cp.float32).reshape(3,4)

# 2. Export it to a DLPack “capsule”
dlpack_capsule = cp_arr.toDlpack()

# 3. Import that capsule into PyTorch
#    torch.from_dlpack is an alias for torch.utils.dlpack.from_dlpack
torch_tensor = torch.from_dlpack(dlpack_capsule)

print(torch_tensor)
# tensor([[ 0.,  1.,  2.,  3.],
#         [ 4.,  5.,  6.,  7.],
#         [ 8.,  9., 10., 11.]], device='cuda:0')


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], device='cuda:0')


In [2]:
# torch_tensor is a CUDA tensor
cap_back = torch.utils.dlpack.to_dlpack(torch_tensor)
cp_again = cp.from_dlpack(cap_back)


In [3]:
tarr = torch.randn(10)
print(tarr)

tensor([-1.4794e-01,  2.1893e-01,  2.8232e-01,  2.2854e+00,  1.0350e+00,
         4.6454e-01, -4.6705e-01, -5.4989e-01,  6.5477e-04,  4.1714e-01])


In [4]:
print(tarr*2.3)

tensor([-3.4027e-01,  5.0355e-01,  6.4934e-01,  5.2564e+00,  2.3804e+00,
         1.0685e+00, -1.0742e+00, -1.2647e+00,  1.5060e-03,  9.5942e-01])


In [5]:
from functools import partial

def test_fun(x, y, z):
    print(x, y, z)

par_fun = partial(test_fun, 3, 4)

par_fun(1)

3 4 1


In [6]:

print("PyTorch CUDA version:", torch.version.cuda)
print("CuPy runtime version:", cp.cuda.runtime.runtimeGetVersion())
print("CuPy driver  version:", cp.cuda.runtime.driverGetVersion())


PyTorch CUDA version: 12.8
CuPy runtime version: 12080
CuPy driver  version: 12090


In [7]:
import corrcal

hera_cal is not installed. Some gridding features unavailable.
pyfof is not installed. Some gridding features unavailable.


In [8]:
corrcal.optimize.grad_nll?


Signature:
corrcal.optimize.grad_nll(
    gains,
    cov,
    data,
    ant_1_inds,
    ant_2_inds,
    scale=1,
    phs_norm_fac=inf,
)
Docstring:
Calculate the gradient of the negative log-likelihood.

This is the gradient with respect to the real/imaginary per-antenna gains.
See Eq. ?? of Pascua+ 25 for details of what is being calculated.

Parameters
----------
same as nll. fill this out later.
File:      ~/corrcal/corrcal/optimize.py
Type:      function